export const restaurants = [
  {
    id: 'dieselAndDuke',
    name: 'Diesel And Duke',
    type: 'burgers',
    visited: 'true',
    location: 'take-out',
    alcohol: 'none',
    price: 'cheap',
    locationColor: '#E2711D',
    alcoholColor: '#969A97',
  },
  {
    id: 'wurstbar',
    name: 'Wurstbar',
    type: 'sausage',
    visited: 'true',
    location: 'dine-in',
    alcohol: 'beer',
    price: 'affordable',
    locationColor: '#00B4D8',
    alcoholColor: '#ffba49',
  },
  {
    id: 'porta',
    name: 'Porta',
    type: 'pizza',
    visited: 'true',
    location: 'dine-in',
    alcohol: 'beer',
    price: 'affordable',
    locationColor: '#00B4D8',
    alcoholColor: '#ffba49',
  },
  {
    id: 'aniRamen',
    name: 'Ani Ramen',
    type: 'ramen',
    visited: 'true',
    location: 'dine-in',
    alcohol: 'cocktails',
    price: 'average',
    locationColor: '#00B4D8',
    alcoholColor: '#8436c8',
  },
  {
    id: 'surfCity',
    name: 'Surf City',
    type: 'seafood',
    visited: 'true',
    location: 'dine-in',
    alcohol: 'beer',
    price: 'affordable',
    locationColor: '#00B4D8',
    alcoholColor: '#ffba49',
  },
  {
    id: 'zeppelinHall',
    name: 'Zeppelin Hall',
    type: 'barbeque',
    visited: 'true',
    location: 'dine-in',
    alcohol: 'beer',
    price: 'affordable',
    locationColor: '#00B4D8',
    alcoholColor: '#ffba49',
  },
  {
    id: 'gringos',
    name: 'Gringos',
    type: 'mexican',
    visited: 'true',
    location: 'dine-in',
    alcohol: 'cocktails',
    price: 'average',
    locationColor: '#00B4D8',
    alcoholColor: '#8436c8',
  },
  {
    id: 'hudsonHound',
    name: 'Hudson Hound',
    type: 'irish',
    visited: 'false',
    location: 'dine-in',
    alcohol: 'beer',
    price: 'average',
    locationColor: '#00B4D8',
    alcoholColor: '#ffba49',
  },
  {
    id: 'loFi',
    name: 'Lo Fi',
    type: 'pizza',
    visited: 'true',
    location: 'dine-in',
    alcohol: 'beer',
    price: 'affordable',
    locationColor: '#00B4D8',
    alcoholColor: '#ffba49',
  },
  {
    id: 'theBoil',
    name: 'The Boil',
    type: 'seafood',
    visited: 'true',
    location: 'dine-in',
    alcohol: 'beer',
    price: 'affordable',
    locationColor: '#00B4D8',
    alcoholColor: '#ffba49',
  },
  {
    id: 'hardGrove',
    name: 'Hard Grove',
    type: 'steakhouse',
    visited: 'true',
    location: 'dine-in',
    alcohol: 'cocktails',
    price: 'average',
    locationColor: '#00B4D8',
    alcoholColor: '#8436c8',
  },
  {
    id: 'hamiltonPork',
    name: 'Hamilton Pork',
    type: 'barbeque',
    visited: 'true',
    location: 'dine-in',
    alcohol: 'beer',
    price: 'average',
    locationColor: '#00B4D8',
    alcoholColor: '#ffba49',
  },
  {
    id: 'leftBank',
    name: 'Left Bank',
    type: 'burgers',
    visited: 'true',
    location: 'dine-in',
    alcohol: 'beer',
    price: 'average',
    locationColor: '#00B4D8',
    alcoholColor: '#ffba49',
  },
  {
    id: 'senHai',
    name: 'Sen Hai',
    type: 'chinese',
    visited: 'true',
    location: 'take-out',
    alcohol: 'none',
    price: 'cheap',
    locationColor: '#E2711D',
    alcoholColor: '#969A97',
  },
  {
    id: 'cloveGarden',
    name: 'Clove Garden',
    type: 'indian',
    visited: 'true',
    location: 'take-out',
    alcohol: 'none',
    price: 'average',
    locationColor: '#E2711D',
    alcoholColor: '#969A97',
  },
  {
    id: 'southHouse',
    name: 'South House',
    type: 'steakhouse',
    visited: 'true',
    location: 'dine-in',
    alcohol: 'cocktails',
    price: 'average',
    locationColor: '#00B4D8',
    alcoholColor: '#8436c8',
  },
  {
    id: 'theAshford',
    name: 'The Ashford',
    type: 'american',
    visited: 'false',
    location: 'dine-in',
    alcohol: 'cocktails',
    price: 'expensive',
    locationColor: '#00B4D8',
    alcoholColor: '#8436c8',
  },
  {
    id: 'taqueria',
    name: 'Taqueria',
    type: 'mexican',
    visited: 'true',
    location: 'dine-in',
    alcohol: 'beer',
    price: 'average',
    locationColor: '#00B4D8',
    alcoholColor: '#ffba49',
  },
  {
    id: 'tacoria',
    name: 'Tacoria',
    type: 'mexican',
    visited: 'true',
    location: 'take-out',
    alcohol: 'none',
    price: 'affordable',
    locationColor: '#E2711D',
    alcoholColor: '#969A97',
  },
  {
    id: 'graceOMalleys',
    name: 'Grace OMalleys',
    type: 'irish',
    visited: 'false',
    location: 'dine-in',
    alcohol: 'cocktails',
    price: 'average',
    locationColor: '#00B4D8',
    alcoholColor: '#8436c8',
  },
  {
    id: 'tonyBaloneys',
    name: 'Tony Baloneys',
    type: 'pizza',
    visited: 'true',
    location: 'take-out',
    alcohol: 'none',
    price: 'affordable',
    locationColor: '#E2711D',
    alcoholColor: '#969A97',
  }
]
export const transformPrice = (restaurants) => {
  switch(restaurants) {
    case 'cheap':
        return '$';
      case 'affordable':
        return '$$';
      case 'average':
        return '$$$';
      case 'expensive':
        return '$$$$';
      default: 
        return '$$$$$'
  }
}