export const restaurants = [
  {
    id: 'wurstbar',
    name: 'Wurstbar',
    type: 'sausage',
    visited: true,
  },
  {
    id: 'porta',
    name: 'Porta',
    type: 'pizza',
    visited: true,
  },
  {
    id: 'aniRamen',
    name: 'Ani Ramen',
    type: 'ramen',
    visited: true,
  },
  {
    id: 'surfCity',
    name: 'Surf City',
    type: 'seafood',
    visited: true,
  },
  {
    id: 'zeppelinHall',
    name: 'Zeppelin Hall',
    type: 'barbeque',
    visited: true,
  },
  {
    id: 'gringos',
    name: 'Gringos',
    type: 'mexican',
    visited: true,
  },
  {
    id: 'hudsonHound',
    name: 'Hudon Hound',
    type: 'irish',
    visited: false,
  },
  {
    id: 'loFi',
    name: 'Lo Fi',
    type: 'pizza',
    visited: true,
  },
  {
    id: 'theBoil',
    name: 'The Boil',
    type: 'seafood',
    visited: true,
  },
  {
    id: 'hardGrove',
    name: 'Hard Grove',
    type: 'steakhouse',
    visited: true,
  },
  {
    id: 'hamiltonPork',
    name: 'Hamilton Pork',
    type: 'barbeque',
    visited: true,
  },
  {
    id: 'leftBank',
    name: 'Left Bank',
    type: 'burgers',
    visited: true,
  },
  {
    id: 'dieselAndDuke',
    name: 'Diesel And Duke',
    type: 'burgers',
    visited: true,
  },
  {
    id: 'senHai',
    name: 'Sen Hai',
    type: 'chinese',
    visited: true,
  },
  {
    id: 'cloveGarden',
    name: 'Clove Garden',
    type: 'indian',
    visited: true,
  },
  {
    id: 'southHouse',
    name: 'South House',
    type: 'steakhouse',
    visited: true,
  },
  {
    id: 'theAshford',
    name: 'The Ashford',
    type: 'american',
    visited: true,
  },
  {
    id: 'taqueria',
    name: 'Taqueria',
    type: 'mexican',
    visited: true,
  },
  {
    id: 'tacoria',
    name: 'Tacoria',
    type: 'mexican',
    visited: true,
  },
  {
    id: 'graceOMalleys',
    name: 'Grace OMalleys',
    type: 'irish',
    visited: false,
  },
  {
    id: 'tonyBaloneys',
    name: 'Tony Baloneys',
    type: 'pizza',
    visited: true,
  }
]